FROM wezuo/ortmodule-sccl-pytorch-cuda-cudnn-devel:v2.1

# Need a fix for apex issue https://github.com/NVIDIA/apex/issues/694
#RUN sed -i "s/next_functions\[1\]/next_functions\[0\]/" /opt/conda/envs/TorchNightly/lib/python3.8/site-packages/apex/amp/utils.py

RUN echo "Preparing container for MOE experiment"

###################################################################################
# Temporary Installation Directory
###################################################################################
ENV STAGE_DIR=/tmp
RUN mkdir -p ${STAGE_DIR}

###################################################################################
# Testing packages
###################################################################################
RUN pip install fairscale
RUN pip install git+https://github.com/microsoft/tutel.git@e51df1ca64be59eae3691bc1c64b20a201de1009
#https://github.com/mpi4py/mpi4py/issues/157#issuecomment-1001022274
ENV SETUPTOOLS_USE_DISTUTILS=stdlib
RUN pip install ruamel.yaml mpi4py pytest-mpi pytest coverage

###################################################################################
# Install onnxruntime-training
###################################################################################
# use nightly as it has necessary fixes and no regressions, switch to stable once released
RUN pip install --no-deps --force --pre "onnxruntime-training<1.11.0.dev20220216001" -f https://download.onnxruntime.ai/onnxruntime_nightly_cu111.html
RUN pip install --no-deps torch-ort -f https://onnxruntimepackages.z14.web.core.windows.net/onnxruntime_nightly_torch190.cu111.html
# workaround for build issues due to no GPU
ENV TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX"
RUN python -m torch_ort.configure
